# server
server.port=90
server.pool-size=2

timezone.zone=Europe/Moscow

GeneratorFile.charset=utf-8
GeneratorFile.output-dir=out/cards

send.url=http://localhost:8090/upload
send.chunk.size=1048576

grpc.host=localhost
grpc.port=50051