
CREATE USER ACC_APP_ADAPTER IDENTIFIED BY adapter_password;
GRANT CONNECT, RESOURCE TO ACC_APP_ADAPTER;


CREATE SEQUENCE GRU.GRU_VISTA_TAB_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE GRU.GRU_REJECT_TAB_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE GRU.GRU_VISTA_TAB (
    ID NUMBER(12),
    SYSTEMACCOUNT VARCHAR2(32 BYTE),
    CURRENCY VARCHAR2(3 BYTE),
    XALFA NUMBER(23,3),
    OPERATION VARCHAR2(3 BYTE),
    TIME_STAMP DATE DEFAULT sysdate,
    POM_ID NUMBER(12),
    UTERRARIO NUMBER(18),
    OLDTBAL NUMBER(23,3),
    NEWTBAL NUMBER(23,3),
    ADD_INFO VARCHAR2(100 BYTE),
    FILE_ID NUMBER(12),
    FOC_STATUS VARCHAR2(64 BYTE) DEFAULT 'WAIT',
    FOC_TS DATE,
    FOC_TYPE VARCHAR2(10 BYTE) DEFAULT 'IMMEDIATE',
    SVFE_LOAD_ID VARCHAR2(36 BYTE)
);

CREATE TABLE GRU.GRU_REJECT_TAB (
    ID NUMBER(12),
    SYSTEMACCOUNT VARCHAR2(32 BYTE),
    VISTA_TAB_ID NUMBER(12),
    UTERRARIO NUMBER(9),
    OLDTBAL NUMBER(20,3),
    NEWTBAL NUMBER(20,3),
    FRONT_TIMESTAMP DATE,
    FRONT_STATUS VARCHAR2(3 BYTE),
    REJECT_DESC VARCHAR2(256 BYTE),
    CHECK_STATUS VARCHAR2(3 BYTE),
    CHECK_DESC VARCHAR2(256 BYTE),
    CHECK_USER VARCHAR2(20 BYTE),
    CHECK_TIMESTAMP DATE,
    SVFE_LOAD_ID VARCHAR2(256 BYTE)
);


CREATE TABLE ACC_APP_ADAPTER.APP_ADAPTER_CONFIG (
    ID NUMBER(12) PRIMARY KEY,
    SYSTEMID VARCHAR2(255 BYTE),
    EVENT_TYPE VARCHAR2(255 BYTE),
    ENTITY_TYPE VARCHAR2(255 BYTE),
    TOPIC_IN VARCHAR2(255 BYTE),
    STATUS_IN NUMBER(1),
    TOPIC_OUT VARCHAR2(255 BYTE),
    STATUS_OUT NUMBER(1),
    INS_TS DATE DEFAULT sysdate,
    UPD_TS DATE DEFAULT sysdate
);

CREATE TABLE ACC_APP_ADAPTER.APP_ADAPTER_TRANS (
    ID NUMBER PRIMARY KEY,
    SYSTEM_ID VARCHAR2(256 BYTE),
    REQUEST_ID VARCHAR2(256 BYTE),
    EVENT_TYPE VARCHAR2(256 BYTE),
    DATA CLOB,
    STATUS VARCHAR2(256 BYTE),
    RESP_CODE VARCHAR2(16 BYTE),
    RESP_DESC VARCHAR2(256 BYTE),
    INS_TS DATE DEFAULT sysdate,
    UPD_TS DATE DEFAULT sysdate
);

CREATE TABLE ACC_APP_ADAPTER.APP_ADAPTER_IO_MSGS (
    ID NUMBER PRIMARY KEY,
    TRANS_ID NUMBER(18),
    MSG_TYPE VARCHAR2(64 BYTE),
    DIR VARCHAR2(16 BYTE),
    MSG CLOB,
    INS_TS DATE DEFAULT sysdate,
    NODE_ID VARCHAR2(8 BYTE)
);


CREATE SEQUENCE ACC_APP_ADAPTER.APP_ADAPTER_TRANS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE ACC_APP_ADAPTER.APP_ADAPTER_IO_MSGS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


GRANT SELECT, INSERT, UPDATE, DELETE ON ACC_APP_ADAPTER.APP_ADAPTER_CONFIG TO GRU;
GRANT SELECT, INSERT, UPDATE, DELETE ON ACC_APP_ADAPTER.APP_ADAPTER_TRANS TO GRU;
GRANT SELECT, INSERT, UPDATE, DELETE ON ACC_APP_ADAPTER.APP_ADAPTER_IO_MSGS TO GRU;
GRANT SELECT ON ACC_APP_ADAPTER.APP_ADAPTER_TRANS_SEQ TO GRU;
GRANT SELECT ON ACC_APP_ADAPTER.APP_ADAPTER_IO_MSGS_SEQ TO GRU;

INSERT INTO ACC_APP_ADAPTER.APP_ADAPTER_CONFIG (ID, SYSTEMID, EVENT_TYPE, ENTITY_TYPE, TOPIC_IN, STATUS_IN, TOPIC_OUT, STATUS_OUT)
VALUES (1, 'GRU', 'BALANCE', 'ACCOUNT', 'gru.balance.in', 1, 'gru.balance.out', 1);

INSERT INTO ACC_APP_ADAPTER.APP_ADAPTER_CONFIG (ID, SYSTEMID, EVENT_TYPE, ENTITY_TYPE, TOPIC_IN, STATUS_IN, TOPIC_OUT, STATUS_OUT)
VALUES (2, 'GRU', 'FOOD', 'CARD', 'gru.food.in', 1, 'gru.food.out', 1);

COMMIT;